language: python
python: 3.7
install:
    - pip install --upgrade pip
    - pip install 'setuptools>=18.5'
    - pip install 'cwltool==1.0.20181217162649'
    - pip install 'ruamel.yaml==0.15.77'
script: find . -name '*.cwl' | xargs -n 1 cwltool --validate
